Update patch set 4
Patch Set 4:

some compiler issues solved, still some left:

device/samsung/espresso-common/DeviceSettings/src/com/cyanogenmod/settings/device/KernelModule.java:25: error: cannot find symbol
        setContentView(R.layout.kernel_module);
        ^
  symbol:   method setContentView(int)
  location: class KernelModule
device/samsung/espresso-common/DeviceSettings/src/com/cyanogenmod/settings/device/KernelModule.java:28: error: no suitable method found for makeText(KernelModule,String,int)
            Toast.makeText(this, SEC_DOC_KEYBOARD + " module does not exist", Toast.LENGTH_LONG).show();
                 ^
    method Toast.makeText(Context,int,int) is not applicable
      (actual argument KernelModule cannot be converted to Context by method invocation conversion)
    method Toast.makeText(Context,CharSequence,int) is not applicable
      (actual argument KernelModule cannot be converted to Context by method invocation conversion)
device/samsung/espresso-common/DeviceSettings/src/com/cyanogenmod/settings/device/KernelModule.java:29: error: cannot find symbol
            finish();
            ^
  symbol:   method finish()
  location: class KernelModule
device/samsung/espresso-common/DeviceSettings/src/com/cyanogenmod/settings/device/KernelModule.java:34: error: cannot find symbol
        CheckBox checkBox = (CheckBox) findViewById(R.id.checkbox);
                                       ^
  symbol:   method findViewById(int)
  location: class KernelModule
device/samsung/espresso-common/DeviceSettings/src/com/cyanogenmod/settings/device/KernelModule.java:62: error: cannot find symbol
        getSharedPreferences("prefs", MODE_PRIVATE).edit().putBoolean("moduleactive", active).apply();
                                      ^
  symbol:   variable MODE_PRIVATE
  location: class KernelModule
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
5 errors

Patch-set: 4