Update patch set 2
Patch Set 2: Code-Review-2

need some help here :(

device/samsung/espresso-common/DeviceSettings/src/com/cyanogenmod/settings/device/Startup.java:31: error: method onReceive(Context,Intent) is already defined in class Startup
    public void onReceive(Context context, Intent intent) {
                ^
device/samsung/espresso-common/DeviceSettings/src/com/cyanogenmod/settings/device/DeviceSettings.java:59: error: cannot find symbol
        mTabsAdapter.addTab(bar.newTab().setText(R.category_kernel_module_title),
                                                  ^
  symbol:   variable category_kernel_module_title
  location: class R
device/samsung/espresso-common/DeviceSettings/src/com/cyanogenmod/settings/device/KernelModule.java:23: error: onCreate(Bundle) in KernelModule cannot override onCreate(Bundle) in Fragment
    protected void onCreate(Bundle savedInstanceState) {
                   ^
  attempting to assign weaker access privileges; was public
device/samsung/espresso-common/DeviceSettings/src/com/cyanogenmod/settings/device/KernelModule.java:25: error: cannot find symbol
        setContentView(R.layout.kernel_module);
        ^
  symbol:   method setContentView(int)
  location: class KernelModule
device/samsung/espresso-common/DeviceSettings/src/com/cyanogenmod/settings/device/KernelModule.java:28: error: no suitable method found for makeText(KernelModule,String,int)
            Toast.makeText(this, SEC_DOC_KEYBOARD + " module does not exist", Toast.LENGTH_LONG).show();
                 ^
    method Toast.makeText(Context,int,int) is not applicable
      (actual argument KernelModule cannot be converted to Context by method invocation conversion)
    method Toast.makeText(Context,CharSequence,int) is not applicable
      (actual argument KernelModule cannot be converted to Context by method invocation conversion)
device/samsung/espresso-common/DeviceSettings/src/com/cyanogenmod/settings/device/KernelModule.java:29: error: cannot find symbol
            finish();
            ^
  symbol:   method finish()
  location: class KernelModule
device/samsung/espresso-common/DeviceSettings/src/com/cyanogenmod/settings/device/KernelModule.java:34: error: cannot find symbol
        CheckBox checkBox = (CheckBox) findViewById(R.id.checkbox);
                                       ^
  symbol:   method findViewById(int)
  location: class KernelModule
device/samsung/espresso-common/DeviceSettings/src/com/cyanogenmod/settings/device/KernelModule.java:62: error: cannot find symbol
        getSharedPreferences("prefs", MODE_PRIVATE).edit().putBoolean("moduleactive", active).apply();
                                      ^
  symbol:   variable MODE_PRIVATE
  location: class KernelModule
device/samsung/espresso-common/DeviceSettings/src/com/cyanogenmod/settings/device/SU.java:22: error: TAG has private access in FragmentActivity
            Log.i(DeviceSettings.TAG, "SU initialized");
                                ^
device/samsung/espresso-common/DeviceSettings/src/com/cyanogenmod/settings/device/SU.java:27: error: TAG has private access in FragmentActivity
            Log.e(DeviceSettings.TAG, "Failed to run shell as su");
                                ^
device/samsung/espresso-common/DeviceSettings/src/com/cyanogenmod/settings/device/SU.java:60: error: TAG has private access in FragmentActivity
            Log.i(DeviceSettings.TAG, "SU closed: " + process.exitValue());
                                ^
device/samsung/espresso-common/DeviceSettings/src/com/cyanogenmod/settings/device/Startup.java:34: error: cannot find symbol
            su.runCommand("insmod " + MainActivity.SEC_DOC_KEYBOARD_PATH);
                                      ^
  symbol:   variable MainActivity
  location: class Startup
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
12 errors

Patch-set: 2
Reviewer: Andreas Blaesius <1000016@f8201d64-d729-4630-b91d-5f8be02869f0>
Label: Code-Review=-2